### ISSUE TITLE
Organization charts metrics are missing and/or wrong

### ISSUE THREAD

**Issue by noirbizarre** [opendatateam/udata-piwik#16]
## Detailed Description
Organizations chart is broken in administration and only display zero values.
A quick check shows that the metric API is providing the correct values to the widget but they are cumulative instead of being by day

## Context
As a producer, I want to have the right values to display

## Possible Implementation
Fix it !

## Your Environment
udata 1.0.9
udata-piwik 0.9.1

**Comment by abulte** [comment]
This should be fixed by https://gitlab.incubateur.net/data.gouv.fr/infra/commit/5ca4b3298bc0d45c27d23f970a97e35c73aa7ca8 (update piwik auth token on prod)

**Comment by abulte** [comment]
All good now! Except historical data of course.

<img width="1193" alt="capture d ecran 2017-11-17 09 52 14" src="https://user-images.githubusercontent.com/119625/32938603-067976c8-cb7d-11e7-8094-435d10103c30.png">
