### ISSUE TITLE
job `piwik-current-metrics` is faling silently

### ISSUE THREAD

**Issue by jordanguedj** [opendatateam/udata-piwik#229]
For example, in case the job cannot query Piwik, it sill embeds the result into JSON data without failing:
```
{'result': 'error', 'message': 'You are currently not allowed to log in because you had too many failed logins, try again later.'}
{'module': 'API', 'idSite': 109, 'method': 'Actions.getDownloads', 'format': 'json', 'token_auth': 'xxxxxxxxxxxxxxxxxxx', 'period': 'day', 'expanded': 1, 'date': '2021-02-08'}
```
The improvement would be to check the result and raise.

**Comment by abulte** [comment]
`requests.raise_for_status()` might help (if the status code from Matomo is coherent).

**Comment by quaxsze** [comment]
The piwik API return a `200`code even when failing.

Only the body differs:
```
{
    "result": "error",
    "message": "You can't access this resource as it requires 'view' access."
}
```

**Comment by abulte** [comment]
I guess we need to test for result == error then.
