### ISSUE TITLE
Versioning package to correspond to master

### ISSUE THREAD

**Issue by freesoul** [opendatateam/udata-piwik#267]
Basically the part related to PIWIK_GOALS in the template.html try to use a uData object which does not exist and creates an error in the console

This has been removed from the master branch, but it is not apparent in the latest packaged version 2.1.4

Could you please release it? Thanks

**Comment by abulte** [comment]
Hi, there's a 3.1 release on pypi https://pypi.org/project/udata-piwik/. We don't release on GitHub anymore, sorry for the confusion.
